#!/usr/bin/env php
<?php

require __DIR__.'/../../vendor/autoload.php';

use JMS\JobQueueBundle\Console\Application;
use JMS\JobQueueBundle\Tests\Functional\AppKernel;

set_time_limit(0);

$kernel = new AppKernel(getenv('SYMFONY_CONFIG') ?: 'persistent_db.yaml');
$application = new Application($kernel);
$application->run();
